"""
Dreamer AI Phase 1 — Mock Agents
Simulate Domain and Technical agent behavior for trial run.
"""

import os
import json
import asyncio
from dataclasses import dataclass
from typing import Dict, Optional
from state_bus import StateBus, Message
from sandbox_manager import SandboxManager, SandboxConfig, ResourceLockedError


@dataclass
class AgentContext:
    name: str
    bus: StateBus
    sandbox: SandboxManager
    trace_id: str


class CurriculumAgent:
    """Domain Agent: designs lesson specifications."""

    def __init__(self, ctx: AgentContext):
        self.ctx = ctx

    async def execute(self, task_id: str, params: Dict) -> Dict:
        await self._report_status(task_id, "running")

        # Simulate work: create lesson spec
        spec = {
            "topic": params.get("topic", "General"),
            "grade_level": params.get("grade_level", 1),
            "learning_objectives": [
                "Understand core concepts",
                "Apply in practice problems",
                "Demonstrate mastery",
            ],
            "estimated_duration_minutes": 45,
            "materials_needed": ["Whiteboard", "Worksheets"],
            "api_endpoints": [
                "GET /api/lessons",
                "GET /api/lessons/{id}",
                "POST /api/lessons",
            ],
            "db_tables": [
                {
                    "name": "lessons",
                    "columns": [
                        "id UUID PRIMARY KEY",
                        "title TEXT NOT NULL",
                        "grade_level INTEGER",
                        "content JSONB",
                        "created_at TIMESTAMP DEFAULT NOW()",
                    ],
                }
            ],
        }

        # Write to sandbox
        ws_path = self.ctx.sandbox.get_workspace_path(
            f"feature/curriculum-{task_id[:8]}"
        )
        spec_path = os.path.join(ws_path, params.get("output_file", "lesson_spec.json"))
        with open(spec_path, "w") as f:
            json.dump(spec, f, indent=2)

        await self.ctx.sandbox.commit_output(
            ws_name=f"feature/curriculum-{task_id[:8]}",
            files=[spec_path],
            status="success",
        )

        await self._report_status(task_id, "completed")
        return {"spec_file": spec_path, "spec": spec}

    async def _report_status(self, task_id: str, status: str):
        msg = Message.create(
            topic=f"task.{task_id}.status",
            payload={"taskId": task_id, "agent": "curriculum", "status": status},
            source="agent:curriculum",
            trace_id=self.ctx.trace_id,
        )
        await self.ctx.bus.publish(msg)


class BackendAgent:
    """Technical Agent: generates API route code."""

    def __init__(self, ctx: AgentContext):
        self.ctx = ctx

    async def execute(self, task_id: str, params: Dict) -> Dict:
        await self._report_status(task_id, "running")

        # Read input spec if provided
        spec = {}
        spec_from = params.get("spec_from", "")
        if spec_from:
            # Find spec file from curriculum agent output
            curriculum_ws = f"feature/curriculum-{spec_from[:8]}"
            spec_path = os.path.join(
                self.ctx.sandbox.base_dir, curriculum_ws, "lesson_spec.json"
            )
            if os.path.exists(spec_path):
                with open(spec_path) as f:
                    spec = json.load(f)

        # Generate API code
        endpoints = spec.get("api_endpoints", ["GET /api/lessons"])
        routes_code = self._generate_routes(endpoints)

        ws_path = self.ctx.sandbox.get_workspace_path(f"feature/be-{task_id[:8]}")
        api_file = os.path.join(ws_path, params.get("output_file", "lesson_api.py"))
        with open(api_file, "w") as f:
            f.write(routes_code)

        # Simulate some work time
        await asyncio.sleep(0.3)

        await self.ctx.sandbox.commit_output(
            ws_name=f"feature/be-{task_id[:8]}",
            files=[api_file],
            status="success",
        )

        await self._report_status(task_id, "completed")
        return {"api_file": api_file, "endpoints": endpoints}

    def _generate_routes(self, endpoints: list) -> str:
        code = '''"""Lesson API — Auto-generated by BackendAgent"""

from flask import Blueprint, request, jsonify

lesson_bp = Blueprint("lessons", __name__, url_prefix="/api/lessons")

'''
        for ep in endpoints:
            method, path = ep.split(" ", 1)
            method_lower = method.lower()
            route_path = path.replace("/api/lessons", "").strip() or "/"
            code += f"""
@lesson_bp.route("{route_path}", methods=["{method}"])
def {method_lower}_lessons{'_by_id' if '{id}' in route_path else ''}():
    return jsonify({{"status": "ok", "method": "{method}"}})
"""
        return code

    async def _report_status(self, task_id: str, status: str):
        msg = Message.create(
            topic=f"task.{task_id}.status",
            payload={"taskId": task_id, "agent": "be", "status": status},
            source="agent:be",
            trace_id=self.ctx.trace_id,
        )
        await self.ctx.bus.publish(msg)


class DatabaseAgent:
    """Technical Agent: generates SQL migration code."""

    def __init__(self, ctx: AgentContext):
        self.ctx = ctx

    async def execute(self, task_id: str, params: Dict) -> Dict:
        await self._report_status(task_id, "running")

        # Read input spec
        spec = {}
        spec_from = params.get("spec_from", "")
        if spec_from:
            curriculum_ws = f"feature/curriculum-{spec_from[:8]}"
            spec_path = os.path.join(
                self.ctx.sandbox.base_dir, curriculum_ws, "lesson_spec.json"
            )
            if os.path.exists(spec_path):
                with open(spec_path) as f:
                    spec = json.load(f)

        # Generate SQL migration
        tables = spec.get("db_tables", [])
        sql = self._generate_migration(tables)

        ws_path = self.ctx.sandbox.get_workspace_path(f"feature/db-{task_id[:8]}")
        sql_file = os.path.join(
            ws_path, params.get("output_file", "lesson_schema.sql")
        )
        with open(sql_file, "w") as f:
            f.write(sql)

        # Simulate work
        await asyncio.sleep(0.3)

        await self.ctx.sandbox.commit_output(
            ws_name=f"feature/db-{task_id[:8]}",
            files=[sql_file],
            status="success",
        )

        await self._report_status(task_id, "completed")
        return {"sql_file": sql_file, "tables": [t["name"] for t in tables]}

    def _generate_migration(self, tables: list) -> str:
        sql = """-- Migration: Lesson Management Schema
-- Auto-generated by DatabaseAgent

"""
        for table in tables:
            name = table["name"]
            columns = table.get("columns", [])
            sql += f"CREATE TABLE {name} (\n"
            sql += "    " + ",\n    ".join(columns)
            sql += "\n);\n\n"
        return sql

    async def _report_status(self, task_id: str, status: str):
        msg = Message.create(
            topic=f"task.{task_id}.status",
            payload={"taskId": task_id, "agent": "db", "status": status},
            source="agent:db",
            trace_id=self.ctx.trace_id,
        )
        await self.ctx.bus.publish(msg)
