-- Dreamer AI Phase 7 — Plan Proposal DB Schema (D11 Plan-Proposal Flow v1.1)
-- plan_proposals: 8-week (variable duration_weeks) learning plan generated by
-- Plan Agent → rule-based validation → Dreamer AI teacher human gate
-- (approve / request_changes / reject) → one-shot adjustment (v1.1).
--
-- v1.1 design decisions (spec §3 / §5 / §6):
--   - duration_weeks is a COLUMN not a constant — schema supports 1-year
--     extension without migration.
--   - weeks / baseline_ref / cost_summary / review / adjustment stored as JSON
--     text columns (SQLite), keeping the top-level row queryable.
--   - Idempotency: one pending_review per student enforced by partial unique
--     index (spec §6: 同一学生同时只有一份 pending_review).
--   - Audit trail: approved → adjusted v2 supersedes v1; rejected/superseded
--     rows are kept forever (spec §3: 审计痕唔准冇).
--
-- Idempotent: CREATE TABLE IF NOT EXISTS — safe to re-run.

PRAGMA journal_mode=WAL;

CREATE TABLE IF NOT EXISTS plan_proposals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    plan_id TEXT NOT NULL UNIQUE,
    version INTEGER NOT NULL DEFAULT 1,
    student_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending_review',
    lang_code TEXT NOT NULL DEFAULT 'zh-hk',
    age_band TEXT NOT NULL DEFAULT 'P4-P6',
    duration_weeks INTEGER NOT NULL DEFAULT 8,
    cycle_label TEXT NOT NULL DEFAULT '',
    weeks TEXT NOT NULL DEFAULT '[]',
    parent_summary TEXT NOT NULL DEFAULT '',
    baseline_ref TEXT NOT NULL DEFAULT '{}',
    cost_summary TEXT NOT NULL DEFAULT '{}',
    review TEXT NOT NULL DEFAULT '{}',
    adjustment TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT '',
    updated_at TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_plan_proposals_student
    ON plan_proposals(student_id, status, version);

-- 幂等硬闸：同一学生同时最多一份 pending_review
CREATE UNIQUE INDEX IF NOT EXISTS uq_plan_proposals_one_pending
    ON plan_proposals(student_id) WHERE status = 'pending_review';
